### PR TITLE
Sync testing 2.10.14 -> stable 2.10.14

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Review by Croydon — APPROVED** [review]

**Comment by jmarrec** [comment]
Travis is failing on only one platform of the matrix (`CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_CLANG_VERSIONS=9`), due to missing prebuilt package for bzip:

```
conans.errors.ConanException: Missing prebuilt package for 'bzip2/1.0.8'
```

https://travis-ci.com/bincrafters/conan-cpprestsdk/jobs/268414657#L678

Can this drop in?

**Comment by uilianries** [comment]
@Croydon we can't use boost 1.71 Cpp REST SDK only works with 1.69

https://travis-ci.com/bincrafters/conan-cpprestsdk/builds/141161591

**Comment by uilianries** [comment]
> Travis is failing on only one platform of the matrix (`CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_CLANG_VERSIONS=9`), due to missing prebuilt package for bzip:
> 
> ```
> conans.errors.ConanException: Missing prebuilt package for 'bzip2/1.0.8'
> ```
> 
> [travis-ci.com/bincrafters/conan-cpprestsdk/jobs/268414657#L678](https://travis-ci.com/bincrafters/conan-cpprestsdk/jobs/268414657#L678)
> 
> Can this drop in?

https://github.com/conan-io/conan-center-index/issues/503

**Comment by Croydon** [comment]
> @Croydon we can't use boost 1.71 Cpp REST SDK only works with 1.69

From my understanding this was fixed in https://github.com/bincrafters/conan-websocketpp/pull/5

**Comment by Croydon** [comment]
> Travis is failing on only one platform of the matrix (CONAN_DOCKER_IMAGE=conanio/clang9 CONAN_CLANG_VERSIONS=9), due to missing prebuilt package for bzip:

This is a non-blocking issue, we can ignore it for this pull request

**Comment by jmarrec** [comment]
> @Croydon we can't use boost 1.71 Cpp REST SDK only works with 1.69
> 
> https://travis-ci.com/bincrafters/conan-cpprestsdk/builds/141161591

@uilianries See the latest: https://travis-ci.com/bincrafters/conan-cpprestsdk/builds/141546167

**Comment by uilianries** [comment]
> 
> 
> > @Croydon we can't use boost 1.71 Cpp REST SDK only works with 1.69
> 
> From my understanding this was fixed in [bincrafters/conan-websocketpp#5](https://github.com/bincrafters/conan-websocketpp/pull/5)

that's great! thanks!

**Comment by prince-chrismc** [comment]
I tried install the latest version but there is an issue with the OpenSSL dependency.

The official package name is "OpenSSL"

https://bintray.com/conan-community/conan/OpenSSL%3Aconan

https://github.com/conan-io/conan-center-index/blob/8a07dd95d9479f8998f77fdcd5d68a334b763778/recipes/openssl/ALL/conanfile.py#L592

I get the following error
> conan info cpprestsdk/2.10.14@bincrafters/stable
WARN: websocketpp/0.8.1@bincrafters/stable: requirement zlib/1.2.11 overridden by cpprestsdk/2.10.14@bincrafters/stable to zlib/1.2.11@conan/stable
WARN: websocketpp/0.8.1@bincrafters/stable: requirement boost/1.71.0 overridden by cpprestsdk/2.10.14@bincrafters/stable to boost/1.69.0@conan/stable
ERROR: Failed requirement 'openssl/1.1.1d' from 'websocketpp/0.8.1@bincrafters/stable'
ERROR: Requested 'openssl/1.1.1d' but found case incompatible 'OpenSSL'
Case insensitive filesystem can't manage this

The error in this case is reported by websocketpp but I can see the same issue would arise here.

**Comment by jmarrec** [comment]
@prince-chrismc You have to remove existing older packages bearing the OpenSSL name that are in your cache

Basically `rm -Rf ~/.conan/data/OpenSSL`

**Comment by prince-chrismc** [comment]
Firstly I apologize for commenting in the wrong repo, I just discovered the meta repo for issues.
I will raise my issue in https://github.com/bincrafters/community/issues/1069

I would love to however some of my other deps use the conan-center spelling.

**Comment by uilianries** [comment]
Weird error, cpprestsdk was not able to find Boost random on Mac. However, I can't reproduce such error on my Mac environment. I just add cmake_find_package generator, let's see the result.

**Pull request merged**
