### PR TITLE
- split x86 and x64 builds

### PR DESCRIPTION
**Pull request by SSE4**
DON"T MERGE UNTIL BUILD IS GREEN

### CODE REVIEW

**Comment by SSE4** [comment]
@solvingj build is green - pls review

**Comment by solvingj** [comment]
@uilianries , can you revise at next opportunity?

**Comment by uilianries** [comment]
LGTM

**Review by uilianries — COMMENTED** [review]
LGTM

**Review by uilianries — APPROVED** [review]

**Comment by uilianries** [comment]
The build continuous-integration/appveyor/branch won't work.

You could set travis and appveyor/pr as mandatory

**Comment by SSE4** [comment]
appveyor/branch has to be disabled (not needed)

**Pull request merged**
